baseURI: http://airqa.bsbportal.com
baseURI1: http://127.0.0.1:4723


env: prod
platform: android
page_spec_file_root: PageSpecs
email: vishnuvishmech@gmail.com
password: Vishnu321


android:
  app: Flipkart.apk
  appPackage: "com.flipkart.android"
  appActivity: "com.flipkart.android.SplashActivity"
  deviceName: emulator-5554
  platformVersion: "11"
  server: http://127.0.0.1:4723/wd/hub
  udid: emulator-5554

  
ios:
  app: MyAirtelQA.ipa
  deviceName: iPhone XR
  platformVersion: "12.2"
  udid: CA2B4060-D26A-41E9-AE22-2F1752504AD5
  bundleId: in.bsb.myairtel.inhouse
  automationName: XCUITest
  server: http://0.0.0.0:4723/wd/hub

  



